# coding: utf-8

# flake8: noqa
"""
    CVAT REST API

    REST API for Computer Vision Annotation Tool (CVAT)  # noqa: E501

    OpenAPI spec version: v1
    Contact: nikita.manovich@intel.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from cvat_api.models.about import About
from cvat_api.models.attribute import Attribute
from cvat_api.models.attribute_val import AttributeVal
from cvat_api.models.body import Body
from cvat_api.models.client_file import ClientFile
from cvat_api.models.data import Data
from cvat_api.models.data_meta import DataMeta
from cvat_api.models.dataset_format import DatasetFormat
from cvat_api.models.dataset_formats import DatasetFormats
from cvat_api.models.exception import Exception
from cvat_api.models.file_info import FileInfo
from cvat_api.models.frame_meta import FrameMeta
from cvat_api.models.inline_response200 import InlineResponse200
from cvat_api.models.inline_response2001 import InlineResponse2001
from cvat_api.models.inline_response2002 import InlineResponse2002
from cvat_api.models.job import Job
from cvat_api.models.label import Label
from cvat_api.models.labeled_data import LabeledData
from cvat_api.models.labeled_image import LabeledImage
from cvat_api.models.labeled_shape import LabeledShape
from cvat_api.models.labeled_track import LabeledTrack
from cvat_api.models.log_event import LogEvent
from cvat_api.models.login import Login
from cvat_api.models.password_change import PasswordChange
from cvat_api.models.password_reset import PasswordReset
from cvat_api.models.password_reset_confirm import PasswordResetConfirm
from cvat_api.models.project import Project
from cvat_api.models.remote_file import RemoteFile
from cvat_api.models.restricted_register import RestrictedRegister
from cvat_api.models.rq_status import RqStatus
from cvat_api.models.segment import Segment
from cvat_api.models.server_file import ServerFile
from cvat_api.models.simple_job import SimpleJob
from cvat_api.models.task import Task
from cvat_api.models.tracked_shape import TrackedShape
from cvat_api.models.user import User
from cvat_api.models.user_agreement import UserAgreement
