# coding: utf-8

"""
    CVAT REST API

    REST API for Computer Vision Annotation Tool (CVAT)  # noqa: E501

    OpenAPI spec version: v1
    Contact: nikita.manovich@intel.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cvat_api
from cvat_api.models.segment import Segment  # noqa: E501
from cvat_api.rest import ApiException


class TestSegment(unittest.TestCase):
    """Segment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSegment(self):
        """Test Segment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cvat_api.models.segment.Segment()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
